[package]
name = "raydium"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
stb_image_rust = "2.27.2"
stb_image_write_rust = "1.16.1"
