[package]
name = "raydium"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.6"
log = "0.4.19"
rand = "0.8.5"
sdl2 = "0.35.2"

